### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by dreson4** [BartoszJarocki/android-boilerpipe#4]
I'm using the library for fetching Images in an AsyncTask activity, I used the jar lib present in the libs directory, everything works fine in debugging mode, but doesn't work when I compile in release mode. I'm receiving this error

> java.lang.RuntimeException: An error occurred while executing doInBackground()
>                                                                  at android.os.AsyncTask$3.done(AsyncTask.java:309)
>                                                                  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
>                                                                  at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
>                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
>                                                                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
>                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>                                                                  at java.lang.Thread.run(Thread.java:818)
>                                                               Caused by: java.lang.ExceptionInInitializerError
>                                                                  at org.cyberneko.html.HTMLScanner.scanEntityRef(HTMLScanner.java:1386)
>                                                                  at org.cyberneko.html.HTMLScanner$ContentScanner.scanAttribute(HTMLScanner.java:2955)
>                                                                  at org.cyberneko.html.HTMLScanner$ContentScanner.scanAttribute(HTMLScanner.java:2785)
>                                                                  at org.cyberneko.html.HTMLScanner$ContentScanner.scanStartElement(HTMLScanner.java:2639)
>                                                                  at org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2071)
>                                                                  at org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:891)
>                                                                  at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:491)
>                                                                  at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:444)
>                                                                  at mf.org.apache.xerces.parsers.XMLParser.parse(XMLParser.java:109)
>                                                                  at mf.org.apache.xerces.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1199)
>                                                                  at de.l3s.boilerpipe.sax.BoilerpipeSAXInput.getTextDocument(BoilerpipeSAXInput.java:61)
>                                                                  at de.l3s.boilerpipe.sax.BoilerpipeSAXInput.getTextDocument(BoilerpipeSAXInput.java:49)
>                                                                  at de.l3s.boilerpipe.sax.ImageExtractor.process(ImageExtractor.java:109)
>                                                                  at com.ulicast.Feed.ImageLinkExtractor.doInBackground(ImageLinkExtractor.java:43)
>                                                                  at com.ulicast.Feed.ImageLinkExtractor.doInBackground(ImageLinkExtractor.java:22)
>                                                                  at android.os.AsyncTask$2.call(AsyncTask.java:295)
>                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
>                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
>                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
>                                                                  at java.lang.Thread.run(Thread.java:818) 
>                                                               Caused by: java.lang.NullPointerException: in == null
>                                                                  at java.util.Properties.load(Properties.java:246)
>                                                                  at org.cyberneko.html.HTMLEntities.load0(HTMLEntities.java:102)
>                                                                  at org.cyberneko.html.HTMLEntities.<clinit>(HTMLEntities.java:54)
>                                                                  at org.cyberneko.html.HTMLScanner.scanEntityRef(HTMLScanner.java:1386) 
>                                                                  at org.cyberneko.html.HTMLScanner$ContentScanner.scanAttribute(HTMLScanner.java:2955) 
>                                                                  at org.cyberneko.html.HTMLScanner$ContentScanner.scanAttribute(HTMLScanner.java:2785) 
>                                                                  at org.cyberneko.html.HTMLScanner$ContentScanner.scanStartElement(HTMLScanner.java:2639) 
>                                                                  at org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2071) 
>                                                                  at org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:891) 
>                                                                  at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:491) 
>                                                                  at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:444) 
>                                                                  at mf.org.apache.xerces.parsers.XMLParser.parse(XMLParser.java:109) 
>                                                                  at mf.org.apache.xerces.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1199) 
>                                                                  at de.l3s.boilerpipe.sax.BoilerpipeSAXInput.getTextDocument(BoilerpipeSAXInput.java:61) 
>                                                                  at de.l3s.boilerpipe.sax.BoilerpipeSAXInput.getTextDocument(BoilerpipeSAXInput.java:49) 
>                                                                  at de.l3s.boilerpipe.sax.ImageExtractor.process(ImageExtractor.java:109) 
>                                                                  at com.ulicast.Feed.ImageLinkExtractor.doInBackground(ImageLinkExtractor.java:43) 
>                                                                  at com.ulicast.Feed.ImageLinkExtractor.doInBackground(ImageLinkExtractor.java:22) 
>                                                                  at android.os.AsyncTask$2.call(AsyncTask.java:295) 
>                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
>                                                                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
>                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
>                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
>                                                                  at java.lang.Thread.run(Thread.java:818) 

And here is the AsyncTask class, tracing the error seems to be starting at when I assign LIst<Image> imgUrls = ie.process(url, extractor)

``public class ImageLinkExtractor extends AsyncTask<String, Void, String> {

```
private ImageLinkExtractorListener listener;

public ImageLinkExtractor(ImageLinkExtractorListener listener) {
    this.listener = listener;
}

@Override
protected void onPostExecute(String s) {
    listener.onExecuteFinish(s);
}

@Override
protected String doInBackground(String... params) {
    String image = null;

    try {
        BoilerpipeExtractor extractor = ArticleExtractor.getInstance();
        ImageExtractor ie = ImageExtractor.getInstance();
        URL url = new URL(params[0]);
        List<Image> imgUrls = ie.process(url, extractor);
        Collections.sort(imgUrls);
        if (!imgUrls.isEmpty()) image = imgUrls.get(0).getSrc();
    } catch (Exception e) {
        e.printStackTrace();
    }

    return image;
}

public interface ImageLinkExtractorListener {
    void onExecuteFinish(String imageUrl);
}
```

}

I have also tried couple conditions in proguard but nothing seems to work. 

> -keep class org.apache.xerces.parsers.SAXParser
> -keep class de.l3s.*

**Comment by dreson4** [comment]
I got it to work in the end, the solution was to keep class in proguard-rules. Here is what worked:

> -keep class de.l3s.**
> -keep class org.cyberneko.**
> -keep class org.apache.xerces.**
